/**
 * OBD-II DTC (Diagnostic Trouble Code) Lookup Table
 * Covers P (Powertrain), B (Body), C (Chassis), U (Network) codes.
 * severity: 'critical' | 'warning' | 'healthy'
 */

const DTC_DB = {
  // ── P0: Fuel & Air Metering ────────────────────────────────────────────────
  P0100: { description: 'Mass Air Flow (MAF) Circuit Malfunction', severity: 'warning' },
  P0101: { description: 'Mass Air Flow (MAF) Circuit Range/Performance Problem', severity: 'warning' },
  P0102: { description: 'Mass Air Flow (MAF) Circuit Low Input', severity: 'warning' },
  P0103: { description: 'Mass Air Flow (MAF) Circuit High Input', severity: 'warning' },
  P0104: { description: 'Mass Air Flow (MAF) Circuit Intermittent', severity: 'warning' },
  P0105: { description: 'Manifold Absolute Pressure (MAP) Circuit Malfunction', severity: 'warning' },
  P0106: { description: 'Manifold Absolute Pressure (MAP) Circuit Range/Performance', severity: 'warning' },
  P0107: { description: 'Manifold Absolute Pressure (MAP) Circuit Low Input', severity: 'warning' },
  P0108: { description: 'Manifold Absolute Pressure (MAP) Circuit High Input', severity: 'warning' },
  P0110: { description: 'Intake Air Temperature (IAT) Circuit Malfunction', severity: 'warning' },
  P0111: { description: 'Intake Air Temperature (IAT) Circuit Range/Performance', severity: 'warning' },
  P0112: { description: 'Intake Air Temperature (IAT) Circuit Low Input', severity: 'warning' },
  P0113: { description: 'Intake Air Temperature (IAT) Circuit High Input', severity: 'warning' },
  P0115: { description: 'Engine Coolant Temperature (ECT) Circuit Malfunction', severity: 'warning' },
  P0116: { description: 'Engine Coolant Temperature (ECT) Circuit Range/Performance', severity: 'warning' },
  P0117: { description: 'Engine Coolant Temperature (ECT) Circuit Low Input', severity: 'warning' },
  P0118: { description: 'Engine Coolant Temperature (ECT) Circuit High Input', severity: 'warning' },
  P0120: { description: 'Throttle Position Sensor (TPS) A Circuit Malfunction', severity: 'warning' },
  P0121: { description: 'Throttle Position Sensor (TPS) A Circuit Range/Performance', severity: 'warning' },
  P0122: { description: 'Throttle Position Sensor (TPS) A Circuit Low Input', severity: 'warning' },
  P0123: { description: 'Throttle Position Sensor (TPS) A Circuit High Input', severity: 'critical' },
  P0125: { description: 'Insufficient Coolant Temperature for Closed Loop Fuel Control', severity: 'warning' },
  P0128: { description: 'Coolant Thermostat Below Regulating Temperature', severity: 'warning' },
  P0130: { description: 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 1)', severity: 'warning' },
  P0131: { description: 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)', severity: 'warning' },
  P0132: { description: 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)', severity: 'warning' },
  P0133: { description: 'O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)', severity: 'warning' },
  P0134: { description: 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 1)', severity: 'warning' },
  P0135: { description: 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)', severity: 'warning' },
  P0136: { description: 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 2)', severity: 'warning' },
  P0137: { description: 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)', severity: 'warning' },
  P0138: { description: 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 2)', severity: 'warning' },
  P0140: { description: 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 2)', severity: 'warning' },
  P0141: { description: 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)', severity: 'warning' },
  P0150: { description: 'O2 Sensor Circuit Malfunction (Bank 2, Sensor 1)', severity: 'warning' },
  P0155: { description: 'O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 1)', severity: 'warning' },
  P0171: { description: 'System Too Lean (Bank 1) — Fuel mixture too lean, possible vacuum leak or faulty MAF', severity: 'warning' },
  P0172: { description: 'System Too Rich (Bank 1) — Fuel mixture too rich, possible faulty injector or O2 sensor', severity: 'warning' },
  P0174: { description: 'System Too Lean (Bank 2) — Lean fuel mixture on bank 2', severity: 'warning' },
  P0175: { description: 'System Too Rich (Bank 2) — Rich fuel mixture on bank 2', severity: 'warning' },

  // ── P02: Fuel Injectors ────────────────────────────────────────────────────
  P0200: { description: 'Injector Circuit Malfunction', severity: 'critical' },
  P0201: { description: 'Injector Circuit Malfunction — Cylinder 1', severity: 'critical' },
  P0202: { description: 'Injector Circuit Malfunction — Cylinder 2', severity: 'critical' },
  P0203: { description: 'Injector Circuit Malfunction — Cylinder 3', severity: 'critical' },
  P0204: { description: 'Injector Circuit Malfunction — Cylinder 4', severity: 'critical' },
  P0205: { description: 'Injector Circuit Malfunction — Cylinder 5', severity: 'critical' },
  P0206: { description: 'Injector Circuit Malfunction — Cylinder 6', severity: 'critical' },

  // ── P03: Ignition / Misfire ────────────────────────────────────────────────
  P0300: { description: 'Random/Multiple Cylinder Misfire Detected', severity: 'critical' },
  P0301: { description: 'Cylinder 1 Misfire Detected', severity: 'critical' },
  P0302: { description: 'Cylinder 2 Misfire Detected', severity: 'critical' },
  P0303: { description: 'Cylinder 3 Misfire Detected', severity: 'critical' },
  P0304: { description: 'Cylinder 4 Misfire Detected', severity: 'critical' },
  P0305: { description: 'Cylinder 5 Misfire Detected', severity: 'critical' },
  P0306: { description: 'Cylinder 6 Misfire Detected', severity: 'critical' },
  P0307: { description: 'Cylinder 7 Misfire Detected', severity: 'critical' },
  P0308: { description: 'Cylinder 8 Misfire Detected', severity: 'critical' },
  P0320: { description: 'Ignition/Distributor Engine Speed Input Circuit Malfunction', severity: 'critical' },
  P0325: { description: 'Knock Sensor 1 Circuit Malfunction (Bank 1)', severity: 'warning' },
  P0326: { description: 'Knock Sensor 1 Circuit Range/Performance (Bank 1)', severity: 'warning' },
  P0335: { description: 'Crankshaft Position Sensor A Circuit Malfunction', severity: 'critical' },
  P0336: { description: 'Crankshaft Position Sensor A Circuit Range/Performance', severity: 'critical' },
  P0340: { description: 'Camshaft Position Sensor A Circuit Malfunction (Bank 1)', severity: 'critical' },
  P0341: { description: 'Camshaft Position Sensor A Circuit Range/Performance (Bank 1)', severity: 'critical' },
  P0351: { description: 'Ignition Coil A Primary/Secondary Circuit Malfunction', severity: 'warning' },
  P0352: { description: 'Ignition Coil B Primary/Secondary Circuit Malfunction', severity: 'warning' },
  P0353: { description: 'Ignition Coil C Primary/Secondary Circuit Malfunction', severity: 'warning' },
  P0354: { description: 'Ignition Coil D Primary/Secondary Circuit Malfunction', severity: 'warning' },

  // ── P04: Auxiliary Emission Controls ──────────────────────────────────────
  P0400: { description: 'Exhaust Gas Recirculation (EGR) Flow Malfunction', severity: 'warning' },
  P0401: { description: 'Exhaust Gas Recirculation (EGR) Flow Insufficient Detected', severity: 'warning' },
  P0402: { description: 'Exhaust Gas Recirculation (EGR) Flow Excessive Detected', severity: 'warning' },
  P0410: { description: 'Secondary Air Injection System Malfunction', severity: 'warning' },
  P0420: { description: 'Catalyst System Efficiency Below Threshold (Bank 1) — Catalytic converter degraded', severity: 'warning' },
  P0421: { description: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)', severity: 'warning' },
  P0430: { description: 'Catalyst System Efficiency Below Threshold (Bank 2)', severity: 'warning' },
  P0440: { description: 'Evaporative Emission Control System Malfunction', severity: 'warning' },
  P0441: { description: 'Evaporative Emission Control System Incorrect Purge Flow', severity: 'warning' },
  P0442: { description: 'Evaporative Emission Control System Leak Detected (Small Leak)', severity: 'warning' },
  P0443: { description: 'Evaporative Emission Control System Purge Control Valve Circuit Malfunction', severity: 'warning' },
  P0446: { description: 'Evaporative Emission Control System Vent Control Circuit Malfunction', severity: 'warning' },
  P0455: { description: 'Evaporative Emission Control System Leak Detected (Large Leak)', severity: 'warning' },
  P0456: { description: 'Evaporative Emission Control System Leak Detected (Very Small Leak)', severity: 'warning' },
  P0480: { description: 'Cooling Fan 1 Control Circuit Malfunction', severity: 'warning' },
  P0481: { description: 'Cooling Fan 2 Control Circuit Malfunction', severity: 'warning' },

  // ── P05: Speed / Idle Control ──────────────────────────────────────────────
  P0500: { description: 'Vehicle Speed Sensor Malfunction', severity: 'warning' },
  P0501: { description: 'Vehicle Speed Sensor Range/Performance', severity: 'warning' },
  P0505: { description: 'Idle Air Control System Malfunction', severity: 'warning' },
  P0506: { description: 'Idle Air Control System RPM Lower Than Expected', severity: 'warning' },
  P0507: { description: 'Idle Air Control System RPM Higher Than Expected', severity: 'warning' },

  // ── P06: Computer Output Circuit ──────────────────────────────────────────
  P0600: { description: 'Serial Communication Link Malfunction', severity: 'critical' },
  P0601: { description: 'Internal Control Module Memory Check Sum Error', severity: 'critical' },
  P0602: { description: 'Control Module Programming Error', severity: 'critical' },
  P0603: { description: 'Internal Control Module Keep Alive Memory (KAM) Error', severity: 'critical' },
  P0604: { description: 'Internal Control Module Random Access Memory (RAM) Error', severity: 'critical' },
  P0606: { description: 'PCM Processor Fault', severity: 'critical' },
  P0620: { description: 'Generator Control Circuit Malfunction', severity: 'critical' },
  P0621: { description: 'Generator Lamp "L" Control Circuit Malfunction', severity: 'warning' },
  P0622: { description: 'Generator Field "F" Control Circuit Malfunction', severity: 'critical' },
  P0625: { description: 'Generator Field Terminal Circuit Low', severity: 'critical' },
  P0626: { description: 'Generator Field Terminal Circuit High', severity: 'critical' },
  P0627: { description: 'Fuel Pump "A" Control Circuit Open', severity: 'critical' },
  P0628: { description: 'Fuel Pump "A" Control Circuit Low', severity: 'critical' },
  P0629: { description: 'Fuel Pump "A" Control Circuit High', severity: 'critical' },
  P0630: { description: 'VIN Not Programmed or Incompatible — ECM/PCM', severity: 'warning' },
  P0641: { description: 'Sensor Reference Voltage "A" Circuit Open', severity: 'critical' },
  P0645: { description: 'A/C Clutch Relay Control Circuit Malfunction', severity: 'warning' },
  P0650: { description: 'Malfunction Indicator Lamp (MIL) Control Circuit Malfunction', severity: 'warning' },
  P0660: { description: 'Intake Manifold Tuning Valve Control Circuit Open (Bank 1)', severity: 'warning' },
  P0685: { description: 'ECM/PCM Power Relay Control Circuit Open', severity: 'critical' },
  P0691: { description: 'Cooling Fan 1 Control Circuit Low', severity: 'warning' },
  P0692: { description: 'Cooling Fan 1 Control Circuit High', severity: 'warning' },

  // ── P07: Transmission ──────────────────────────────────────────────────────
  P0700: { description: 'Transmission Control System Malfunction', severity: 'critical' },
  P0701: { description: 'Transmission Control System Range/Performance', severity: 'critical' },
  P0702: { description: 'Transmission Control System Electrical', severity: 'critical' },
  P0703: { description: 'Torque Converter/Brake Switch B Circuit Malfunction', severity: 'warning' },
  P0705: { description: 'Transmission Range Sensor Circuit Malfunction (PRNDL Input)', severity: 'warning' },
  P0706: { description: 'Transmission Range Sensor Circuit Range/Performance', severity: 'warning' },
  P0710: { description: 'Transmission Fluid Temperature Sensor Circuit Malfunction', severity: 'warning' },
  P0711: { description: 'Transmission Fluid Temperature Sensor Circuit Range/Performance', severity: 'warning' },
  P0715: { description: 'Input/Turbine Speed Sensor Circuit Malfunction', severity: 'critical' },
  P0716: { description: 'Input/Turbine Speed Sensor Circuit Range/Performance', severity: 'critical' },
  P0720: { description: 'Output Speed Sensor Circuit Malfunction', severity: 'critical' },
  P0721: { description: 'Output Speed Sensor Circuit Range/Performance', severity: 'critical' },
  P0725: { description: 'Engine Speed Input Circuit Malfunction', severity: 'critical' },
  P0730: { description: 'Incorrect Gear Ratio', severity: 'critical' },
  P0731: { description: 'Gear 1 Incorrect Ratio', severity: 'critical' },
  P0732: { description: 'Gear 2 Incorrect Ratio', severity: 'critical' },
  P0733: { description: 'Gear 3 Incorrect Ratio', severity: 'critical' },
  P0734: { description: 'Gear 4 Incorrect Ratio', severity: 'critical' },
  P0740: { description: 'Torque Converter Clutch Circuit Malfunction', severity: 'critical' },
  P0741: { description: 'Torque Converter Clutch Circuit Performance or Stuck Off', severity: 'critical' },
  P0750: { description: 'Shift Solenoid A Malfunction', severity: 'critical' },
  P0755: { description: 'Shift Solenoid B Malfunction', severity: 'critical' },
  P0760: { description: 'Shift Solenoid C Malfunction', severity: 'critical' },
  P0765: { description: 'Shift Solenoid D Malfunction', severity: 'critical' },
  P0780: { description: 'Shift Malfunction', severity: 'critical' },

  // ── B: Body ────────────────────────────────────────────────────────────────
  B0001: { description: 'Driver Frontal Stage 1 Deployment Control', severity: 'critical' },
  B0002: { description: 'Driver Frontal Stage 2 Deployment Control', severity: 'critical' },
  B0010: { description: 'Passenger Frontal Stage 1 Deployment Control', severity: 'critical' },
  B0051: { description: 'Airbag Warning Lamp Circuit Fault', severity: 'warning' },
  B1000: { description: 'ECU Malfunction', severity: 'critical' },
  B1001: { description: 'Option Configuration Error', severity: 'warning' },
  B1004: { description: 'ECU Failure', severity: 'critical' },
  B1317: { description: 'Battery Voltage High — Charging system overcharging', severity: 'critical' },
  B1318: { description: 'Battery Voltage Low — Weak battery or charging system fault', severity: 'critical' },
  B1325: { description: 'Control Module Power Circuit Low Voltage', severity: 'critical' },
  B1352: { description: 'Ignition Key-In Circuit Failure', severity: 'warning' },
  B1600: { description: 'PATS Ignition Key Transponder Signal Not Received', severity: 'warning' },
  B2477: { description: 'Module Configuration Failure', severity: 'warning' },

  // ── C: Chassis (ABS / Traction / Steering) ────────────────────────────────
  C0031: { description: 'Right Front Wheel Speed Sensor Circuit Malfunction', severity: 'critical' },
  C0034: { description: 'Left Front Wheel Speed Sensor Circuit Malfunction', severity: 'critical' },
  C0037: { description: 'Right Rear Wheel Speed Sensor Circuit Malfunction', severity: 'critical' },
  C0040: { description: 'Left Rear Wheel Speed Sensor Circuit Malfunction', severity: 'critical' },
  C0035: { description: 'Right Front Wheel Speed Sensor Circuit Range/Performance', severity: 'warning' },
  C0041: { description: 'Right Rear Wheel Speed Sensor Circuit Range/Performance', severity: 'warning' },
  C0044: { description: 'Left Rear Wheel Speed Sensor Circuit Range/Performance', severity: 'warning' },
  C0110: { description: 'ABS Motor Circuit Malfunction', severity: 'critical' },
  C0121: { description: 'ABS Valve Relay Circuit Malfunction', severity: 'critical' },
  C0161: { description: 'ABS/TCS Brake Switch Circuit Malfunction', severity: 'warning' },
  C0186: { description: 'Lateral Accelerometer Circuit Malfunction', severity: 'warning' },
  C0196: { description: 'Yaw Rate Circuit Malfunction', severity: 'warning' },
  C0200: { description: 'Right Front Wheel Speed Sensor Circuit Fault', severity: 'critical' },
  C0205: { description: 'Left Front Wheel Speed Sensor Circuit Fault', severity: 'critical' },
  C0210: { description: 'Right Rear Wheel Speed Sensor Circuit Fault', severity: 'critical' },
  C0215: { description: 'Left Rear Wheel Speed Sensor Circuit Fault', severity: 'critical' },
  C0245: { description: 'Wheel Speed Sensor Frequency Error', severity: 'warning' },
  C0265: { description: 'EBCM Relay Circuit Open', severity: 'critical' },
  C0266: { description: 'EBCM Relay Circuit Shorted', severity: 'critical' },
  C0550: { description: 'Electronic Control Unit Performance', severity: 'critical' },
  C0800: { description: 'Device Voltage Reference Output Circuit', severity: 'warning' },
  C1145: { description: 'Right Front Wheel Speed Sensor Input Circuit Fault', severity: 'critical' },
  C1155: { description: 'Left Front Wheel Speed Sensor Input Circuit Fault', severity: 'critical' },
  C1165: { description: 'Right Rear Wheel Speed Sensor Input Circuit Fault', severity: 'critical' },
  C1175: { description: 'Left Rear Wheel Speed Sensor Input Circuit Fault', severity: 'critical' },

  // ── U: Network / Communication ─────────────────────────────────────────────
  U0001: { description: 'High Speed CAN Communication Bus Fault', severity: 'critical' },
  U0010: { description: 'Medium Speed CAN Communication Bus Fault', severity: 'critical' },
  U0019: { description: 'Low Speed CAN Communication Bus Fault', severity: 'critical' },
  U0100: { description: 'Lost Communication with ECM/PCM', severity: 'critical' },
  U0101: { description: 'Lost Communication with Transmission Control Module (TCM)', severity: 'critical' },
  U0102: { description: 'Lost Communication with Transfer Case Control Module', severity: 'critical' },
  U0103: { description: 'Lost Communication with Gear Shift Control Module', severity: 'critical' },
  U0104: { description: 'Lost Communication with Cruise Control Module', severity: 'warning' },
  U0105: { description: 'Lost Communication with Fuel Injector Control Module', severity: 'critical' },
  U0106: { description: 'Lost Communication with Glow Plug Control Module', severity: 'warning' },
  U0107: { description: 'Lost Communication with Throttle Actuator Control Module', severity: 'critical' },
  U0109: { description: 'Lost Communication with Fuel Pump Control Module', severity: 'critical' },
  U0110: { description: 'Lost Communication with Drive Motor Control Module', severity: 'critical' },
  U0111: { description: 'Lost Communication with Battery Energy Control Module', severity: 'critical' },
  U0114: { description: 'Lost Communication with 4-Wheel Drive Clutch Control Module', severity: 'warning' },
  U0121: { description: 'Lost Communication with Anti-Lock Brake System (ABS) Control Module', severity: 'critical' },
  U0122: { description: 'Lost Communication with Vehicle Dynamics Control Module', severity: 'critical' },
  U0123: { description: 'Lost Communication with Yaw Rate Sensor Module', severity: 'warning' },
  U0124: { description: 'Lost Communication with Lateral Acceleration Sensor Module', severity: 'warning' },
  U0126: { description: 'Lost Communication with Steering Angle Sensor Module', severity: 'warning' },
  U0129: { description: 'Lost Communication with Brake System Control Module', severity: 'critical' },
  U0131: { description: 'Lost Communication with Power Steering Control Module', severity: 'warning' },
  U0140: { description: 'Lost Communication with Body Control Module (BCM)', severity: 'critical' },
  U0141: { description: 'Lost Communication with Body Control Module "A"', severity: 'critical' },
  U0142: { description: 'Lost Communication with Body Control Module "B"', severity: 'critical' },
  U0151: { description: 'Lost Communication with Restraints Control Module', severity: 'critical' },
  U0155: { description: 'Lost Communication with Instrument Panel Cluster (IPC) Control Module', severity: 'warning' },
  U0164: { description: 'Lost Communication with HVAC Control Module', severity: 'warning' },
  U0184: { description: 'Lost Communication with Radio', severity: 'warning' },
  U0195: { description: 'Lost Communication with Satellite Radio Receiver', severity: 'warning' },
  U0196: { description: 'Lost Communication with Rear Seat Entertainment Module', severity: 'warning' },
  U0401: { description: 'Invalid Data Received from ECM/PCM', severity: 'critical' },
  U0402: { description: 'Invalid Data Received from Transmission Control Module', severity: 'critical' },
  U0415: { description: 'Invalid Data Received from Anti-Lock Brake System (ABS) Control Module', severity: 'critical' },
  U0422: { description: 'Invalid Data Received from Body Control Module', severity: 'warning' },
  U0423: { description: 'Invalid Data Received from Instrument Panel Control Module', severity: 'warning' },
};

/**
 * Look up a DTC code and return its description and severity.
 * Falls back gracefully for unknown codes.
 * @param {string} code - OBD-II fault code (e.g. "P0420")
 * @returns {{ description: string, severity: string }}
 */
export function lookupDTC(code) {
  const upper = code.trim().toUpperCase();
  if (DTC_DB[upper]) return DTC_DB[upper];

  // Generic fallback based on code prefix
  const prefix = upper.charAt(0);
  const fallbackDescription = {
    P: `Powertrain fault — ${upper}`,
    B: `Body system fault — ${upper}`,
    C: `Chassis/ABS fault — ${upper}`,
    U: `Network/communication fault — ${upper}`,
  }[prefix] ?? `Unknown fault code — ${upper}`;

  return { description: fallbackDescription, severity: 'warning' };
}
